security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:

        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

        logout:
            pattern: ^/api/logout
            stateless: true

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/users$, roles: ROLE_ADMIN } 
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
monolog:
    channels: ['security']
    handlers:
        security:
            type: stream
            path: "%kernel.logs_dir%/security.log"
            level: debug